# BandageMe Configuration (tested with craftbukkit-1.2.5-R1.0)
bandage:
  # material item to use from bukkit's material list (default is set to string)
  bandage-material: STRING
  # percentage to heal a target
  healing-chance: 80
  # how much material to use per use
  usage-amount: 4
  # lowest heal amount (planned)
  heal-low: 1
  # highest heal amount (planned)
  heal-high: 3
  # bandage cool down timer in ticks (planned)
  cool-down: 100