name: BandageMe
main: com.theSwak.BandageMe.BandageMe
version: 0.42
description: Gives the player the ability to use a bandage to heal other players and living creatures. (tested with CB 1.1-R4)
commands:
    bandageme:
        description: BandageMe gives the player an ability to heal other living creatures with a bandage. To activate, Sneak and Right-click on another person or creature.
permissions:
    bandageme.*:
        description: Gives access to all BandageMe commands
        children:
            bandageme.heal: true
    bandageme.heal:
        description: Allows you to heal another living creature or player
        default: true