name: BandageMe
main: com.theSwak.BandageMe.BandageMe
version: 0.50
description: Gives the player the ability to use a bandage to heal other players and living creatures. (tested with 1.2.5-R1.0)
commands:
    bandageme:
        description: to activate- Sneak and Right-click on another person or creature with the bandage in hand
        usage: /bandageme [player]
        permission: bandageme.commands
        permission-message: You don't have the permission - <permission>
permissions:
    bandageme.*:
        description: Gives access to all BandageMe commands
        children:
            bandageme.commands: true
            bandageme.check: true
    bandageme.commands:
        description: Gives access to BandageMe commands
        default: op
    bandageme.check:
        description: Allows you to heal another living creature or player
        default: false
    bandageme.help:
        description: Allows player to flag that they need healing
        default: true