name: BandageMe
main: com.theSwak.BandageMe.BandageMe
version: 0.27
description: Gives the player the ability to heal other living creatures.
commands:
    bandageme:
        description: This is the BandageMe plug-in command.